#!/bin/sh

BOOTSTRAP_DIR=`mktemp -d`
ZERO_EXTERNAL_DIR=`pwd`/external

rm -rf ${ZERO_EXTERNAL_DIR}
mkdir -p ${ZERO_EXTERNAL_DIR}

# Get SDL
cd ${BOOTSTRAP_DIR}
wget http://www.libsdl.org/tmp/SDL-1.3.tar.gz
tar xf SDL-1.3.tar.gz
cd SDL-1.3.0-6050/
./configure --prefix=${ZERO_EXTERNAL_DIR}
make all
make install

# Get glew
cd ${BOOTSTRAP_DIR}
wget https://sourceforge.net/projects/glew/files/glew/1.7.0/glew-1.7.0.tgz
tar xf glew-1.7.0.tgz
cd glew-1.7.0
make
make GLEW_DEST=${ZERO_EXTERNAL_DIR} install

# Get glm
cd ${BOOTSTRAP_DIR}
wget https://sourceforge.net/projects/ogl-math/files/glm-0.9.2.7/glm-0.9.2.7.zip
unzip glm-0.9.2.7.zip
mv glm-0.9.2.7/glm/ ${ZERO_EXTERNAL_DIR}/include

# Get bullet
cd ${BOOTSTRAP_DIR}
wget http://bullet.googlecode.com/files/bullet-2.79-rev2440.tgz
tar xf bullet-2.79-rev2440.tgz
cd bullet-2.79
cmake -DCMAKE_INSTALL_PREFIX=${ZERO_EXTERNAL_DIR} -G "Unix Makefiles"
make
make install

