#!/bin/sh

BOOTSTRAP_DIR=`mktemp -d`
ZERO_EXTERNAL_DIR=`pwd`/external

rm -rf ${ZERO_EXTERNAL_DIR}
mkdir -p ${ZERO_EXTERNAL_DIR}

# Get GLFW
cd ${BOOTSTRAP_DIR}
wget http://sourceforge.net/projects/glfw/files/glfw/2.7.2/glfw-2.7.2.tar.bz2
tar xfj glfw-2.7.2.tar.bz2
cd glfw-2.7.2/
make x11
make PREFIX=${ZERO_EXTERNAL_DIR} x11-install 

# Get glew
cd ${BOOTSTRAP_DIR}
wget https://sourceforge.net/projects/glew/files/glew/1.7.0/glew-1.7.0.tgz
tar xf glew-1.7.0.tgz
cd glew-1.7.0
make
make GLEW_DEST=${ZERO_EXTERNAL_DIR} install

# Get glm
cd ${BOOTSTRAP_DIR}
wget https://sourceforge.net/projects/ogl-math/files/glm-0.9.2.7/glm-0.9.2.7.zip
unzip glm-0.9.2.7.zip
mv glm-0.9.2.7/glm/ ${ZERO_EXTERNAL_DIR}/include

# Get DevIL
cd ${BOOTSTRAP_DIR}
wget http://downloads.sourceforge.net/openil/DevIL-1.7.8.tar.gz
tar xf DevIL-1.7.8.tar.gz
cd devil-1.7.8
./configure --prefix=${ZERO_EXTERNAL_DIR}/external
make
make install

# Get bullet
cd ${BOOTSTRAP_DIR}
wget http://bullet.googlecode.com/files/bullet-2.79-rev2440.tgz
tar xf bullet-2.79-rev2440.tgz
cd bullet-2.79
cmake -DCMAKE_INSTALL_PREFIX=${ZERO_EXTERNAL_DIR} -G "Unix Makefiles"
make
make install

