#!/bin/sh
# pre: install libxmu-dev libxi-dev libfreetype6-dev libjpeg62-dev

BOOTSTRAP_DIR=`mktemp -d`
ZERO_EXTERNAL_DIR=`pwd`/external

rm -rf ${ZERO_EXTERNAL_DIR}
mkdir -p ${ZERO_EXTERNAL_DIR}

# Get SFML
cd ${BOOTSTRAP_DIR}
wget http://www.sfml-dev.org/download/2.0-rc/SFML-2.0-rc-linux-64.tar.bz2
tar xfj SFML-2.0-rc-linux-64.tar.bz2
cd SFML-2.0-rc/
mv * ${ZERO_EXTERNAL_DIR}

# Get glew
cd ${BOOTSTRAP_DIR}
wget http://sourceforge.net/projects/glew/files/glew/1.7.0/glew-1.7.0.tgz
tar xf glew-1.7.0.tgz
cd glew-1.7.0
make
make GLEW_DEST=${ZERO_EXTERNAL_DIR} install

# Get glm
cd ${BOOTSTRAP_DIR}
wget http://sourceforge.net/projects/ogl-math/files/glm-0.9.2.7/glm-0.9.2.7.zip
unzip glm-0.9.2.7.zip
mv glm-0.9.2.7/glm/ ${ZERO_EXTERNAL_DIR}/include

# Get librocket
cd ${BOOTSTRAP_DIR}
git clone https://github.com/lloydw/libRocket.git
cd libRocket/Build
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=${ZERO_EXTERNAL_DIR}
make
make install

# Get boost
cd ${BOOTSTRAP_DIR}
wget http://sourceforge.net/projects/boost/files/boost/1.51.0/boost_1_51_0.tar.gz
tar xf boost_1_51_0.tar.gz
cd boost_1_51_0
mv boost ${ZERO_EXTERNAL_DIR}/include
