all: week01_1 week01_2 week03 xortest

week01_1: week01_1.cpp
	g++ -ggdb -std=c++0x -Wall -Wextra -pedantic -o week01_1 week01_1.cpp 

week01_2: week01_2.cpp
	g++ -ggdb -std=c++0x -Wall -Wextra -pedantic -o week01_2 week01_2.cpp 

week03: week03.cpp
	g++ -ggdb -std=c++0x -Wall -Wextra -pedantic -o week03 week03.cpp -lcrypto++

xortest: xortest.cpp
	g++ -ggdb -std=c++0x -Wall -Wextra -pedantic -o xortest xortest.cpp 
