all: RenderPipeline gamearchitecture

gamearchitecture: gamearchitecture.cpp
	g++ -std=c++0x -Wall -Wextra -pedantic -o gamearchitecture gamearchitecture.cpp 
RenderPipeline: RenderPipeline.cpp
	g++ -std=c++0x -Wall -Wextra -pedantic -o RenderPipeline RenderPipeline.cpp 
